#!/usr/bin/bash
# Version 03282021
# Container based
# Config getcams variables for run_cameras (bash) 

### NOTE! This is the run_cameras (aka getcams) config file, 
# Set preferred file system default before running as service !
# Set during testing via command line args -S and/or -P
# S3 variable means S3 storage access
# POSIX variable means hierarchical file system usage, could be local, CEPH POSIX mounted or NFS mounted
# Use one or the other

set -a  # export all variables

# Following three variables set in both config_runcams_vars and config_getcams_vars
RHOME="/opt/getcams"
TDIR="scratch"
POSIX=1

# hang_limit is the max delay in minutes for logfile updates before considering
# getcams proc is hung  ... must be negative to use in find w/-mmin flag
hang_limit="-10"


S3=0 
S3CMD="s3cmd"
S3CFG="$RHOME/.s3cfg-xfer"
S3ARGS="-c $S3CFG --no-check-md5 --quiet"

RPATH="$RHOME"
epath="$RPATH"
params="$epath/cam_params"
access="$epath/cam_access"

logpath="$RHOME/log"
log="$logpath/runcamlog"
lockpath="$RHOME/lock"
LOCK="$lockpath/RUNCAM_PID"

set +a # stop exporting variables
